[broker]
address = "kafka:29092"
topic = "ccx.ocp.results"
group = "aggregator"
enabled = true
save_offset = true
enable_org_whitelist = false

[server]
address = ":8080"
api_prefix = "/api/insights-results-aggregator/v1/"
api_spec_file = "openapi.json"
debug = true
auth = true
auth_type = "xrh"
use_https = false
enable_cors = true

[processing]
org_whitelist_file = "org_whitelist.csv"

[storage]
db_driver = "postgres"
pg_username = "user"
pg_password = "password"
pg_host = "localhost"
pg_port = 55432
pg_db_name = "aggregator"
pg_params = "sslmode=disable"
log_sql_queries = true

[content]
path = "./tests/content/ok/"

[logging]
debug = true
logging_to_cloud_watch_enabled = false

[cloudwatch]
aws_access_id = "a key id"
aws_secret_key = "tshhhh it is a secret"
aws_session_token = ""
aws_region = "us-east-1"
log_group = "platform-dev"
stream_name = "insights-results-aggregator"
debug = false
